apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "hasura.fullname" . }}"
  labels:
    {{- include "hasura.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      containers:
      - name: hasura-metadata
        image: "{{ .Values.image.repository }}:{{ .Chart.AppVersi>on }}"
      restartPolicy: Never
  backoffLimit: 1
