apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "hasura.fullname" . }}"
  labels:
    {{- include "hasura.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "1"
spec:
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-init-first: "true"
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "internal-app"
        vault.hashicorp.com/agent-inject-secret-database-config: "internal/data/database/config"
        vault.hashicorp.com/agent-inject-template-database-config: |
          {{`{{- with secret "internal/data/database/config" -}}
            export HASURA_GRAPHQL_DATABASE_URL=postgres://{{ .Data.data.username }}:{{ .Data.data.password }}@35.196.127.103:5432/nami
          {{- end }}`}}
    spec:
      serviceAccount: hasura
      containers:
      - name: hasura-metadata
        image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
        command: ["/bin/sh"]
        args:
            ["-c", "source /vault/secrets/database-config && docker-entrypoint.sh"]
        env:
        - name: ACTION_BASE_URL
          value: "http://nami.{{ .Release.Namespace }}.svc.cluster.local"
      restartPolicy: Never
  backoffLimit: 1
