apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: hasura-console
spec:
  hosts:
  - "{{ .Release.Namespace }}.hasura.dev.dmoiseenko.me"
  gateways:
  - istio-system/iap-ingress-gateway
  http:
  - route:
    - destination:
        host: {{ include "hasura.fullname" . }}
        port:
          number: {{ .Values.service.port }}
