replicaCount: 1

nameOverride: ""
fullnameOverride: ""

image:
  repository: ""

service:
  type: ClusterIP
  port: 80

# https://access.crunchydata.com/documentation/postgres-operator/4.6.0/custom-resources/
restoreFrom: ""