apiVersion: crunchydata.com/v1
kind: Pgcluster
metadata:
  annotations:
    current-primary: {{ include "hasura-metadata.fullname" . }}
  labels:
    crunchy-pgha-scope: {{ include "hasura-metadata.fullname" . }}
    deployment-name: {{ include "hasura-metadata.fullname" . }}
    name: {{ include "hasura-metadata.fullname" . }}
    pg-cluster: {{ include "hasura-metadata.fullname" . }}
    pgo-version: 4.6.0
    pgouser: admin
  name: {{ include "hasura-metadata.fullname" . }}
  namespace: pgo
spec:
  BackrestStorage:
    accessmode: ReadWriteMany
    matchLabels: ""
    name: "standard"
    size: 15G
    storageclass: ""
    storagetype: dynamic
    supplementalgroups: ""
  PrimaryStorage:
    accessmode: ReadWriteMany
    matchLabels: ""
    name: {{ include "hasura-metadata.fullname" . }}
    size: 15G
    storageclass: "standard"
    storagetype: dynamic
    supplementalgroups: ""
  ReplicaStorage:
    accessmode: ReadWriteMany
    matchLabels: ""
    name: ""
    size: 15G
    storageclass: "standard"
    storagetype: dynamic
    supplementalgroups: ""
  annotations: {}
  ccpimage: crunchy-postgres-ha
  ccpimageprefix: registry.developers.crunchydata.com/crunchydata
  ccpimagetag: centos8-13.1-4.6.0
  clustername: {{ include "hasura-metadata.fullname" . }}
  database: zoru
  exporterport: "9187"
  limits: {}
  name: {{ include "hasura-metadata.fullname" . }}
  namespace: {{ .Release.Namespace }}
  pgDataSource:
    restoreFrom: ""
    restoreOpts: ""
  pgbadgerport: "10000"
  pgoimageprefix: registry.developers.crunchydata.com/crunchydata
  podAntiAffinity:
    default: preferred
    pgBackRest: preferred
    pgBouncer: preferred
  port: "5432"
  tolerations: []
  user: zoru
  userlabels:
    pgo-version: 4.6.0
