apiVersion: ricoberger.de/v1alpha1
kind: VaultSecret
metadata:
  labels:
    pg-cluster: {{ .Release.Namespace }}-{{ include "zoru.fullname" . }}
  name: {{ .Release.Namespace }}-{{ include "zoru.fullname" . }}-postgres-secret
  namespace: pgo
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
spec:
  path: internal/database/postgres_user
  type: Opaque
