apiVersion: v1
kind: Secret
type: Opaque
metadata:
  labels:
    pg-cluster: {{ .Release.Namespace }}-{{ include "zoru.fullname" . }}
  name: {{ .Release.Namespace }}-{{ include "zoru.fullname" . }}-primaryuser-secret
  namespace: pgo
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
data:
  password: U3VwZXJzZWN1cmVwYXNzd29yZA==
  username: cHJpbWFyeXVzZXI=
