apiVersion: v1
kind: Service
metadata:
  name: {{ include "zoru.fullname" . }}
  labels:
    {{- include "zoru.labels" . | nindent 4 }}
spec:
  type: ExternalName
  externalName: {{ .Release.Namespace }}-zoru.pgo.svc.cluster.local
  ports:
    - port: 5432
