replicaCount: 1

image:
  repository: us-east1-docker.pkg.dev/prj-kon-build-shared-79d7/repo-kon/alpi
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
