apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "nami.labels" . | nindent 4 }}
    hasuraService: custom
  name: {{ include "nami.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "nami.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        {{- include "nami.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - image: hasura/graphql-engine:v1.3.3
        imagePullPolicy: IfNotPresent
        name: {{ .Chart.Name }}
        env:
        - name: HASURA_GRAPHQL_DATABASE_URL
          value: postgres://nami:nami@35.196.127.103:5432/nami
        ## enable the console served by server
        - name: HASURA_GRAPHQL_ENABLE_CONSOLE
          value: "true"
        ## enable debugging mode. It is recommended to disable this in production
        - name: HASURA_GRAPHQL_DEV_MODE
          value: "true"
        - name: HASURA_GRAPHQL_ADMIN_SECRET
          value: "verylongpasswordstring"
        - name: HASURA_GRAPHQL_ENABLED_APIS
          value: "graphql,metadata,config"
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
