apiVersion: v1
kind: Service
metadata:
  name: {{ include "nami.fullname" . }}
  labels:
    {{- include "nami.labels" . | nindent 4 }}
spec:
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: 8080
  selector:
    {{- include "nami.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.type }}
