steps:
  - name: "${_REGISTRY_URL}/helm"
    entrypoint: "/bin/sh"
    args:
    - "-c"
    - |
      cd ./chart
      helm package --app-version ${_COMMIT_SHA} --version 0.0.${_PATCH_NUMBER}+${_COMMIT_SHA}
      curl --data-binary "@nami-0.0.${_PATCH_NUMBER}+${_COMMIT_SHA}.tgz" https://chart-museum-encaxrhdvq-ue.a.run.app/api/charts
    env:
      - "SKIP_CLUSTER_CONFIG=true"
logsBucket: 'gs://$PROJECT_ID/build-log'
