apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "alpi.fullname" . }}
  labels:
    {{- include "alpi.labels" . | nindent 4 }}
spec:
  replicas: 3
  selector:
    matchLabels:
      {{- include "alpi.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "alpi.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
