apiVersion: v1
kind: Service
metadata:
  name: {{ include "alpi.fullname" . }}
  labels:
    {{- include "alpi.labels" . | nindent 4 }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: alpi-1.dev.dmoiseenko.me.
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "alpi.selectorLabels" . | nindent 4 }}
