steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "${_REGISTRY_URL}/alpi:${_COMMIT_SHA}", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_REGISTRY_URL}/alpi:${_COMMIT_SHA}"]
  - name: "gcr.io/$PROJECT_ID/helm"
    entrypoint: "/bin/sh"
    args:
    - "-c"
    - |
      mkdir helm_package
      cd ./helm_package
      helm package ../chart --app-version ${_COMMIT_SHA} --version 0.0.${_PATCH_NUMBER}+${_COMMIT_SHA}
      gsutil cp gs://${_HELM_REPO_PROJECT_ID}/index.yaml .
      helm repo index . --url https://${_HELM_REPO_PROJECT_ID}.storage.googleapis.com --merge ./index.yaml
      gsutil rsync . gs://${_HELM_REPO_PROJECT_ID}
      gsutil -m setmeta -h "Cache-Control:no-cache,max-age=0" gs://${_HELM_REPO_PROJECT_ID}/*.tgz
      gsutil -m setmeta -h "Cache-Control:no-cache,max-age=0" gs://${_HELM_REPO_PROJECT_ID}/index.yaml
    env:
      - "SKIP_CLUSTER_CONFIG=true"
logsBucket: 'gs://$PROJECT_ID/build-log'
