steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "${_REGISTRY_URL}/alpi:${_COMMIT_SHA}", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_REGISTRY_URL}/alpi:${_COMMIT_SHA}"]
  - name: "us-east1-docker.pkg.dev/prj-sh-kon-registry-4846/kon/helm"
    entrypoint: "/bin/sh"
    args:
    - "-c"
    - |
      mkdir helm_package
      cd ./helm_package
      helm package ../chart --app-version ${_COMMIT_SHA} --version 0.0.${_PATCH_NUMBER}+${_COMMIT_SHA}
      gsutil rsync -x ".*tgz$" gs://${_HELM_REPO_BUCKET_NAME}/ .
      helm repo index . --url https://${_HELM_REPO_BUCKET_NAME}.storage.googleapis.com --merge ./index.yaml
      gsutil rsync . gs://${_HELM_REPO_BUCKET_NAME}
      gsutil setmeta -h "Cache-Control:no-cache,max-age=0" gs://${_HELM_REPO_BUCKET_NAME}/index.yaml
    env:
      - "SKIP_CLUSTER_CONFIG=true"
logsBucket: 'gs://$PROJECT_ID/build-log'
