steps:
  - name: "gcr.io/kaniko-project/executor:latest"
    args:
    - --destination=${_REGISTRY_URL}/alpi:${_COMMIT_SHA}
    - --cache=true
  - name: "${_REGISTRY_URL}/helm"
    entrypoint: "/bin/sh"
    args:
    - "-c"
    - |
      cd ./chart
      helm package . --app-version ${_COMMIT_SHA} --version 0.0.${_PATCH_NUMBER}+${_COMMIT_SHA}
      curl --data-binary "@alpi-0.0.${_PATCH_NUMBER}+${_COMMIT_SHA}.tgz" ${_KON_HELM_REPO_URL}/api/charts
    env:
      - "SKIP_CLUSTER_CONFIG=true"
logsBucket: 'gs://$PROJECT_ID/build-log'
