name: alpi

on:
  pull_request:
    paths:
      - alpi/**

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kon
        uses: actions/checkout@v2
        with:
          path: kon

      - name: gcloud setup
        uses: google-github-actions/setup-gcloud@master
        with:
          version: "319.0.0"
          service_account_key: ${{ secrets.SA_KEY_GCP_BUILD }}
          project_id: ${{ secrets.PROJECT_ID_GCP_BUILD }}

      - name: Test
        run: |-
          echo ${{ github.event.pull_request.base.sha }}
          echo ${{ github.event.pull_request.head.sha }}
          echo ${{ github.run_id }}
          echo ${{ github.run_number }}

      - name: Submit Cloud Build
        run: |-
          gcloud builds submit ./kon/alpi --config=./kon/alpi/cloudbuild.yaml \
            --substitutions=_COMMIT_SHA=${{ github.event.pull_request.head.sha }}, \
            _HELM_REPO=test212, \
            _PATCH_NUMBER=${{ github.run_id }}

      - name: Checkout kon-config
        uses: actions/checkout@v2
        with:
          repository: dmoiseenko/kon-config
          token: ${{ secrets.PAT_GITHUB }}
          path: kon-config

      - name: Update kon-config
        run: |
          cd kon-config
          date > generated.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "generated"
          git push
