name: alpi

on: 
  pull_request:
    paths:
      - alpi/**

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID_GCP_BUILD }}

jobs:
  setup-build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: google-github-actions/setup-gcloud@master
      with:
        version: '319.0.0'
        service_account_key: ${{ secrets.SA_KEY_GCP_BUILD }}
        project_id: ${{ secrets.PROJECT_ID_GCP_BUILD }}

    - name: Cloud Build
      run: |-
        gcloud builds submit ./alpi --config=./alpi/cloudbuild.yaml --substitutions=_COMMIT_SHA=$GITHUB_SHA,_HELM_REPO=test212
