name: Close Pull Request

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build:
    name: Close Pull Request
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kon-config
        uses: actions/checkout@v2
        with:
          repository: dmoiseenko/kon-config
          token: ${{ secrets.PAT_GITHUB }}
          path: kon-config

      - name: Update kon-config
        env:
          FEATURE_BRANCH: ${{ github.event.pull_request.head.ref }}
        run: |
          cd kon-config
          ./scripts/remove_feature_branch.py
