name: Merge Pull Request

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Merge Pull Request
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kon-config
        uses: actions/checkout@v2
        with:
          repository: dmoiseenko/kon-config
          token: ${{ secrets.PAT_GITHUB }}
          path: kon-config

      - name: Update kon-config
        env:
          ALPI_VERSION: 0.0.${{ github.run_id }}+${{ github.event.pull_request.head.sha }}
          FEATURE_BRANCH: main
        run: |
          cd kon-config
          ./scripts/update_alpi.py
