name: Merge Pull Request

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Merge Pull Request
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kon-config
        uses: actions/checkout@v2
        with:
          repository: dmoiseenko/kon-config
          token: ${{ secrets.PAT_GITHUB }}
          path: kon-config

      - name: Update kon-config
        env:
          FEATURE_BRANCH: ${{ github.event.pull_request.head.ref }}
        run: |
          cd kon-config
          ./scripts/promote_development_environment.py
